# Site settings
title: A home, and a few pages.
email: protik77@gmail.com
description: > #
url: "protikdas.com"
# twitter_username: protikdas
repository: protik77/protik77.github.io
github_username:  protik77

permalink: /:categories/:year/:month/:day/:title/
contenturl: "/blog/content/"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  #parse_span_html: true
excerpt_separator: <!--more-->

disqus: protik77

# google_analytics_ua: G-5RVR9Q0HMS
# google_analytics_g: G-3JT3JCVFZS

#paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
